# Generated by Django 5.2.6 on 2025-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('email_user', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('rating', models.FloatField()),
                ('positiv_or_negativ', models.CharField(choices=[('1', 'positiv'), ('2', 'negativ')], max_length=10)),
                ('telefon_number', models.CharField(help_text='ex: +380........', max_length=13)),
            ],
        ),
    ]
